/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  entries?: Array<{
    question: string;
    answer: string;
    _type: "entry";
    _key: string;
  }>;
};

export type AboutMe = {
  _id: string;
  _type: "aboutMe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline: string;
  description: string;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  information?: Array<{
    key?: string;
    value?: Array<string>;
    _type: "entry";
    _key: string;
  }>;
  contact?: Array<{
    key?: string;
    value?: string;
    hidden?: boolean;
    _type: "entry";
    _key: string;
  }>;
};

export type SocialMedia = {
  _id: string;
  _type: "socialMedia";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  instagram?: string;
  facebook?: string;
  pinterest?: string;
  tiktok?: string;
  youtube?: string;
};

export type Shipping = {
  _id: string;
  _type: "shipping";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  shippings: Array<{
    name: string;
    time: number;
    price: number;
    _type: "entry";
    _key: string;
  }>;
  worldwideShipping?: boolean;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  currency: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  details?: Array<{
    detail: string;
    answer: string;
    _key: string;
  }>;
  price: number;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  available: boolean;
  featured?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Slug | Faq | AboutMe | SocialMedia | Shipping | Settings | Product | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: SETTINGS
// Query: *[_type == "settings"][0]{title,currency,description}
export type SETTINGSResult = {
  title: string;
  currency: string;
  description: string;
} | null;
// Variable: SHIPPINGS
// Query: *[_type == "shipping"][0]{shippings[] {name,time,'price': price * 100},worldwideShipping}
export type SHIPPINGSResult = {
  shippings: Array<{
    name: string;
    time: number;
    price: number;
  }>;
  worldwideShipping: boolean | null;
} | null;
// Variable: SOCIALMEDIA
// Query: *[_type == "socialMedia"][0]{instagram,facebook,pinterest,tiktok,youtube}
export type SOCIALMEDIAResult = {
  instagram: string | null;
  facebook: string | null;
  pinterest: string | null;
  tiktok: string | null;
  youtube: string | null;
} | null;
// Variable: FAQ
// Query: *[_type == "faq"][0]{entries[] {    answer,    question}}
export type FAQResult = {
  entries: Array<{
    answer: string;
    question: string;
  }> | null;
} | null;
// Variable: ABOUTME
// Query: *[_type == "aboutMe"][0]{headline,description,avatar,information,contact}
export type ABOUTMEResult = {
  headline: string;
  description: string;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  information: Array<{
    key?: string;
    value?: Array<string>;
    _type: "entry";
    _key: string;
  }> | null;
  contact: Array<{
    key?: string;
    value?: string;
    hidden?: boolean;
    _type: "entry";
    _key: string;
  }> | null;
} | null;
// Variable: PRODUCTS
// Query: *[_type == "product"]{    _id,    name,    image,    'price': price * 100,    available}
export type PRODUCTSResult = Array<{
  _id: string;
  name: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price: number;
  available: boolean;
}>;
// Variable: PRODUCT
// Query: *[_id == $id][0]{    _id,    name,    description,    details,    image,    gallery,    'price': price * 100,    available,    defined(featured) => {        featured[]->{        _id,        name,        image,        'price': price * 100,        available        }    },    !defined(featured) => {        'featured': *[_type == "product" && _id != ^._id && available == true][0..3]{        _id,        name,        image,        'price': price * 100,        available        }    }}
export type PRODUCTResult = {
  _id: string;
  name: string;
  description: string;
  details: Array<{
    detail: string;
    answer: string;
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number;
  available: boolean;
  featured: Array<{
    _id: string;
    name: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price: number;
    available: boolean;
  }>;
} | {
  _id: string;
  name: string;
  description: string;
  details: Array<{
    detail: string;
    answer: string;
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number;
  available: boolean;
  featured: Array<{
    _id: string;
    name: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price: number;
    available: boolean;
  }> | null;
} | {
  _id: string;
  name: string;
  description: string;
  details: Array<{
    detail: string;
    answer: string;
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number;
  available: boolean;
} | {
  _id: string;
  name: null;
  description: null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: Array<{
    _id: string;
    name: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price: number;
    available: boolean;
  }>;
} | {
  _id: string;
  name: null;
  description: null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: null;
} | {
  _id: string;
  name: null;
  description: null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
} | {
  _id: string;
  name: null;
  description: string;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: Array<{
    _id: string;
    name: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price: number;
    available: boolean;
  }>;
} | {
  _id: string;
  name: null;
  description: string;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: null;
} | {
  _id: string;
  name: null;
  description: string;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
} | {
  _id: string;
  name: null;
  description: string | null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: Array<{
    _id: string;
    name: string;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    price: number;
    available: boolean;
  }>;
} | {
  _id: string;
  name: null;
  description: string | null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
  featured: null;
} | {
  _id: string;
  name: null;
  description: string | null;
  details: null;
  image: null;
  gallery: null;
  price: null;
  available: null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]{\ntitle,\ncurrency,\ndescription\n}": SETTINGSResult;
    "*[_type == \"shipping\"][0]{\nshippings[] {\nname,\ntime,\n'price': price * 100\n},\nworldwideShipping\n}\n": SHIPPINGSResult;
    "*[_type == \"socialMedia\"][0]{\ninstagram,\nfacebook,\npinterest,\ntiktok,\nyoutube\n}": SOCIALMEDIAResult;
    "*[_type == \"faq\"][0]{\nentries[] {\n    answer,\n    question\n}\n}": FAQResult;
    "*[_type == \"aboutMe\"][0]{\nheadline,\ndescription,\navatar,\ninformation,\ncontact\n}": ABOUTMEResult;
    "*[_type == \"product\"]{\n    _id,\n    name,\n    image,\n    'price': price * 100,\n    available\n}": PRODUCTSResult;
    "*[_id == $id][0]{\n    _id,\n    name,\n    description,\n    details,\n    image,\n    gallery,\n    'price': price * 100,\n    available,\n    defined(featured) => {\n        featured[]->{\n        _id,\n        name,\n        image,\n        'price': price * 100,\n        available\n        }\n    },\n    !defined(featured) => {\n        'featured': *[_type == \"product\" && _id != ^._id && available == true][0..3]{\n        _id,\n        name,\n        image,\n        'price': price * 100,\n        available\n        }\n    }\n}": PRODUCTResult;
  }
}
