import { Rule } from 'sanity'

const Settings = {
    name: 'settings',
    title: 'Site settings',
    type: 'document',
    fields: [
        {
            name: 'title',
            title: 'Site title',
            type: 'string',
            validation: (rule: Rule) => rule.required().max(60),
            defaultValue: 'Untitled',
        },
        {
            name: 'description',
            title: 'Site description',
            type: 'string',
            validation: (rule: Rule) => rule.required().max(300),
            defaultValue: 'Example description',
        },
        {
            name: 'currency',
            title: 'Currency',
            type: 'string',
            validation: (rule: Rule) => rule.required().length(3).uppercase(),
            description: "In three, uppercased letters' format - eg. EUR.",
            defaultValue: 'EUR',
        },
        {
            name: 'shipping',
            title: 'Shipping',
            type: 'object',
            fields: [
                {
                    name: 'shippings',
                    title: 'Shippings',
                    type: 'array',
                    validation: (rule: Rule) => rule.required(),
                    of: [
                        {
                            name: 'entry',
                            title: 'Entry',
                            type: 'object',
                            fields: [
                                {
                                    name: 'name',
                                    title: 'Name',
                                    type: 'string',
                                    validation: (rule: Rule) => rule.required().max(120),
                                },
                                {
                                    name: 'time',
                                    title: 'Estimated delivery time',
                                    description: 'Amount of days.',
                                    type: 'number',
                                    validation: (rule: Rule) => rule.required().greaterThan(0).lessThan(365),
                                },
                                {
                                    name: 'price',
                                    title: 'Price',
                                    type: 'number',
                                    validation: (rule: Rule) => rule.required(),
                                },
                            ],
                        },
                    ],
                },
                {
                    name: 'shippingCountries',
                    title: 'Shipping coutries',
                    description: 'Countries we allow ordering from.',
                    type: 'array',
                    of: [
                        {
                            name: 'country',
                            title: 'Country',
                            type: 'string',
                            validation: (rule: Rule) => rule.required().length(2),
                            options: {
                                list: [
                                    { title: 'Australia', value: 'AU' },
                                    { title: 'Austria', value: 'AT' },
                                    { title: 'Belgium', value: 'BE' },
                                    { title: 'Brazil', value: 'BR' },
                                    { title: 'Bulgaria', value: 'BG' },
                                    { title: 'Canada', value: 'CA' },
                                    { title: 'Croatia', value: 'HR' },
                                    { title: 'Cyprus', value: 'CY' },
                                    { title: 'Czech Republic', value: 'CZ' },
                                    { title: 'Denmark', value: 'DK' },
                                    { title: 'Estonia', value: 'EE' },
                                    { title: 'Finland', value: 'FI' },
                                    { title: 'France', value: 'FR' },
                                    { title: 'Germany', value: 'DE' },
                                    { title: 'Ghana', value: 'GH' },
                                    { title: 'Gibraltar', value: 'GI' },
                                    { title: 'Greece', value: 'GR' },
                                    { title: 'Hong Kong', value: 'HK' },
                                    { title: 'Hungary', value: 'HU' },
                                    { title: 'India', value: 'IN' },
                                    { title: 'Indonesia', value: 'ID' },
                                    { title: 'Ireland', value: 'IE' },
                                    { title: 'Italy', value: 'IT' },
                                    { title: 'Japan', value: 'JP' },
                                    { title: 'Kenya', value: 'KE' },
                                    { title: 'Latvia', value: 'LV' },
                                    { title: 'Liechtenstein', value: 'LI' },
                                    { title: 'Lithuania', value: 'LT' },
                                    { title: 'Luxembourg', value: 'LU' },
                                    { title: 'Malaysia', value: 'MY' },
                                    { title: 'Malta', value: 'MT' },
                                    { title: 'Mexico', value: 'MX' },
                                    { title: 'Netherlands', value: 'NL' },
                                    { title: 'New Zealand', value: 'NZ' },
                                    { title: 'Nigeria', value: 'NG' },
                                    { title: 'Norway', value: 'NO' },
                                    { title: 'Poland', value: 'PL' },
                                    { title: 'Portugal', value: 'PT' },
                                    { title: 'Romania', value: 'RO' },
                                    { title: 'Singapore', value: 'SG' },
                                    { title: 'Slovakia', value: 'SK' },
                                    { title: 'Slovenia', value: 'SI' },
                                    { title: 'South Africa', value: 'ZA' },
                                    { title: 'Spain', value: 'ES' },
                                    { title: 'Sweden', value: 'SE' },
                                    { title: 'Switzerland', value: 'CH' },
                                    { title: 'Thailand', value: 'TH' },
                                    { title: 'United Arab Emirates', value: 'AE' },
                                    { title: 'United Kingdom', value: 'GB' },
                                    { title: 'United States', value: 'US' },
                                ],
                            },
                        },
                    ],
                },
            ],
            validation: (rule: Rule) => rule.required(),
        },
        {
            name: 'landingImage',
            title: 'Landing page image',
            type: 'object',
            fields: [
                {
                    name: 'image',
                    title: 'Image',
                    type: 'image',
                    validation: (rule: Rule) => rule.required(),
                },
                {
                    name: 'overlay',
                    title: 'Dark overlay opacity',
                    type: 'number',
                    description: 'Higher value, darker overlay, in range 0-100',
                    validation: (rule: Rule) => rule.required().min(0).max(100),
                },
            ],
            validation: (rule: Rule) => rule.required(),
        },
    ],
    options: {
        singleton: true,
    },
}

export default Settings
