import { Rule } from 'sanity'

const Shippings = {
    name: 'shipping',
    title: 'Shipping settings',
    type: 'document',
    fields: [
        {
            name: 'shippings',
            title: 'Shippings',
            type: 'array',
            validation: (rule: Rule) => rule.required(),
            of: [
                {
                    name: 'entry',
                    title: 'Entry',
                    type: 'object',
                    fields: [
                        {
                            name: 'name',
                            title: 'Name',
                            type: 'string',
                            validation: (rule: Rule) => rule.required().max(120),
                        },
                        {
                            name: 'time',
                            title: 'Estimated delivery time',
                            description: 'Amount of days.',
                            type: 'number',
                            validation: (rule: Rule) => rule.required().greaterThan(0).lessThan(365),
                        },
                        {
                            name: 'price',
                            title: 'Price',
                            type: 'number',
                            validation: (rule: Rule) => rule.required(),
                        },
                    ],
                },
            ],
        },
        {
            name: 'shippingCountries',
            title: 'Shipping coutries',
            description: 'Countries we allow ordering from.',
            type: 'array',
            of: [
                {
                    name: 'country',
                    title: 'Country',
                    type: 'string',
                    validation: (rule: Rule) => rule.required().length(2),
                    options: {
                        list: [
                            { title: 'Australia', value: 'AU' },
                            { title: 'Austria', value: 'AT' },
                            { title: 'Belgium', value: 'BE' },
                            { title: 'Brazil', value: 'BR' },
                            { title: 'Bulgaria', value: 'BG' },
                            { title: 'Canada', value: 'CA' },
                            { title: 'Croatia', value: 'HR' },
                            { title: 'Cyprus', value: 'CY' },
                            { title: 'Czech Republic', value: 'CZ' },
                            { title: 'Denmark', value: 'DK' },
                            { title: 'Estonia', value: 'EE' },
                            { title: 'Finland', value: 'FI' },
                            { title: 'France', value: 'FR' },
                            { title: 'Germany', value: 'DE' },
                            { title: 'Ghana', value: 'GH' },
                            { title: 'Gibraltar', value: 'GI' },
                            { title: 'Greece', value: 'GR' },
                            { title: 'Hong Kong', value: 'HK' },
                            { title: 'Hungary', value: 'HU' },
                            { title: 'India', value: 'IN' },
                            { title: 'Indonesia', value: 'ID' },
                            { title: 'Ireland', value: 'IE' },
                            { title: 'Italy', value: 'IT' },
                            { title: 'Japan', value: 'JP' },
                            { title: 'Kenya', value: 'KE' },
                            { title: 'Latvia', value: 'LV' },
                            { title: 'Liechtenstein', value: 'LI' },
                            { title: 'Lithuania', value: 'LT' },
                            { title: 'Luxembourg', value: 'LU' },
                            { title: 'Malaysia', value: 'MY' },
                            { title: 'Malta', value: 'MT' },
                            { title: 'Mexico', value: 'MX' },
                            { title: 'Netherlands', value: 'NL' },
                            { title: 'New Zealand', value: 'NZ' },
                            { title: 'Nigeria', value: 'NG' },
                            { title: 'Norway', value: 'NO' },
                            { title: 'Poland', value: 'PL' },
                            { title: 'Portugal', value: 'PT' },
                            { title: 'Romania', value: 'RO' },
                            { title: 'Singapore', value: 'SG' },
                            { title: 'Slovakia', value: 'SK' },
                            { title: 'Slovenia', value: 'SI' },
                            { title: 'South Africa', value: 'ZA' },
                            { title: 'Spain', value: 'ES' },
                            { title: 'Sweden', value: 'SE' },
                            { title: 'Switzerland', value: 'CH' },
                            { title: 'Thailand', value: 'TH' },
                            { title: 'United Arab Emirates', value: 'AE' },
                            { title: 'United Kingdom', value: 'GB' },
                            { title: 'United States', value: 'US' },
                        ],
                    },
                },
            ],
        },
    ],
    options: {
        singleton: true,
    },
}

export default Shippings
